import { Project, Task, Todo } from "@/types";

export const sampleProjects: Project[] = [
  {
    id: "1",
    name: "Website Redesign",
    description: "Complete redesign of the company website with modern UI/UX",
    color: "#3B82F6",
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    tasks: [],
  },
  {
    id: "2",
    name: "Mobile App Development",
    description: "Building a cross-platform mobile application",
    color: "#10B981",
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    tasks: [],
  },
  {
    id: "3",
    name: "Marketing Campaign",
    description: "Q1 marketing campaign for new product launch",
    color: "#F59E0B",
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
    tasks: [],
  },
];

export const sampleTasks: Task[] = [
  {
    id: "1",
    title: "Design new homepage layout",
    description: "Create wireframes and mockups for the new homepage design",
    completed: false,
    priority: "high",
    dueDate: new Date("2024-02-15"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    projectId: "1",
    todos: [],
  },
  {
    id: "2",
    title: "Implement responsive navigation",
    description: "Build mobile-friendly navigation component",
    completed: true,
    priority: "medium",
    dueDate: new Date("2024-01-30"),
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-20"),
    projectId: "1",
    todos: [],
  },
  {
    id: "3",
    title: "Set up development environment",
    description: "Configure React Native development setup",
    completed: false,
    priority: "high",
    dueDate: new Date("2024-01-25"),
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    projectId: "2",
    todos: [],
  },
  {
    id: "4",
    title: "Create user authentication flow",
    description: "Implement login and registration functionality",
    completed: false,
    priority: "medium",
    dueDate: new Date("2024-02-10"),
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    projectId: "2",
    todos: [],
  },
  {
    id: "5",
    title: "Design social media graphics",
    description: "Create visual assets for social media promotion",
    completed: false,
    priority: "low",
    dueDate: new Date("2024-02-01"),
    createdAt: new Date("2024-01-05"),
    updatedAt: new Date("2024-01-05"),
    projectId: "3",
    todos: [],
  },
];

export const sampleTodos: Todo[] = [
  {
    id: "1",
    text: "Research current design trends",
    completed: true,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-16"),
    taskId: "1",
  },
  {
    id: "2",
    text: "Create initial wireframes",
    completed: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    taskId: "1",
  },
  {
    id: "3",
    text: "Get stakeholder approval",
    completed: false,
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-01-15"),
    taskId: "1",
  },
  {
    id: "4",
    text: "Install React Native CLI",
    completed: true,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-11"),
    taskId: "3",
  },
  {
    id: "5",
    text: "Configure Android Studio",
    completed: false,
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-01-10"),
    taskId: "3",
  },
];
